<<<<<<< HEAD
services:
  - type: web
    name: adhd-timer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
=======
services:
  - type: web
    name: adhd-timer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
>>>>>>> d1b740c546afce52bdecf5e0b0ba101821b394ec
    startCommand: python adhd_timer_web.py